---
name: using v2.0.2

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - id: dsv
        uses: delineaxpm/dsv-github-action@v2.0.2
        with:
          domain: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          retrieve: |
            [
             {"secretPath": "ci:dsv-gh-action", "secretKey": "value1", "outputVariable": "RET_1"},
             {"secretPath": "ci:dsv-gh-action", "secretKey": "value1", "outputVariable": "RETURN_VALUE_1"},
             {"secretPath": "ci:dsv-gh-action", "secretKey": "value1", "outputVariable": "RET_2"}
            ]

      - name: step2
        if: always()
        run: |
          echo ${{ env.RET_1 }}

      - name: step3
        if: always()
        run: |
          echo "This is a secret value you shouldn't echo 👉 ${{ env.RETURN_VALUE_1 }}"
